name: project1env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.7.0
  - aom=3.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - babel=2.16.0
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.6
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.7.1
  - folium=0.20.0
  - fontconfig=2.14.1
  - fonttools=4.59.0
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libavif=1.1.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.14.1
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal-core=3.11.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libkml=1.3.0
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lmdb=0.9.29
  - lz4-c=1.9.4
  - mapclassify=2.10.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mesalib=25.1.5
  - minizip=4.0.3
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - munkres=1.1.4
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.17
  - orc=2.1.1
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.7
  - proj=9.3.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=19.0.0
  - pycparser=2.21
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.3
  - pyproj=3.6.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - s2n=1.5.14
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - shapely=2.0.6
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.2.0
  - statsmodels=0.14.5
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.4
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - astroid==3.3.11
      - autopep8==2.3.2
      - cattrs==25.1.1
      - dill==0.4.0
      - flatbuffers==25.2.10
      - isort==6.0.1
      - jh2==5.0.9
      - mccabe==0.7.0
      - nbqa==1.9.1
      - niquests==3.14.1
      - openmeteo-requests==1.6.0
      - openmeteo-sdk==1.20.1
      - py4j==0.10.9.9
      - pycodestyle==2.14.0
      - pylint==3.3.8
      - pyspark==4.0.0
      - python-dotenv==1.1.1
      - qh3==1.5.3
      - requests-cache==1.2.1
      - retry-requests==2.0.0
      - ruff==0.12.9
      - sodapy==2.2.0
      - tokenize-rt==6.2.0
      - tomli==2.2.1
      - tomlkit==0.13.3
      - url-normalize==2.2.1
      - urllib3-future==2.13.901
      - wassima==1.2.2
